[workspace]
members = ["av1an-core", "av1an"]
resolver = "2"

[profile.dev.package.av-scenechange]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true

[profile.ci]
inherits = "release"
lto = "off"
codegen-units = 1024
debug-assertions = true
overflow-checks = true
